name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      # uncomment to enable task distribution
      # - run: npx nx-cloud start-ci-run --distributes-on="5 linux-medium"

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t=lint,test,build --parallel=3
