name: Migrate Recipes

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  migrate-recipes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    name: Migrate Recipes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Migrate script
        run: node migrate.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          title: Nx Migrate update
          body: Update all recipes with nx migrate
          commit-message: migrate recipes
          branch: migrate-recipes
